services:
  - type: web
    name: romulus-clock
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn romulus_clock:app --host 0.0.0.0 --port 8000
