services:
  - type: web
    name: romulus-clock
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
